language: java

sudo: false
dist: trusty

matrix:
  include:
    - jdk: openjdk11
    - jdk: openjdk12
    - jdk: openjdk13

script:
  - gradle build

after_success:
  - gradle jacocoTestReport coveralls
