language: java

sudo: false
dist: trusty

matrix:
  include:
    - jdk: openjdk11
    - jdk: openjdk12
    - jdk: openjdk13

script:
  - ./gradlew build jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
